### ISSUE TITLE
Duplicate output for constants in separate gem

### ISSUE THREAD

**Issue by danfinnie** [yuki24/did_you_mean#51]
Rspec Output
```
  4) CasesController GET #show when user is authorized when a search is taking too long flashes a generic error
     Failure/Error: get :show, id: 'my id'
     NameError:
       uninitialized constant Client::Project::Exceptions::TimeoutException

           Did you mean? Client::Project::Exceptions::HttpTimeoutException


           Did you mean? Client::Project::Exceptions::HttpTimeoutException

     # ./app/controllers/cases_controller.rb:49:in `rescue in show'
     # ./app/controllers/cases_controller.rb:41:in `show'
     # ./spec/controllers/cases_controller_spec.rb:124:in `block (5 levels) in <top (required)>'
     # ./spec/support/database_cleaner.rb:28:in `block (3 levels) in <top (required)>'
     # ./spec/support/database_cleaner.rb:27:in `block (2 levels) in <top (required)>'
```

**Comment by danfinnie** [comment]
Also:

```
$ bundle show did_you_mean
/Users/pivotal/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/did_you_mean-0.9.8
```

**Comment by yuki24** [comment]
Thanks for the bug report! It turns out that:

  *  `Exception#to_s` always creates a new string object if a message is not provided
    ```ruby
    error = ((raise NameError) rescue $!)
    error.to_s.object_id # => 16993800
    error.to_s.object_id # => 16982100
    ```

  * It reuses the same string object if an arbitrary error message is provided

    ```ruby
    msg = "error"
    msg.object_id # => 17177860 

    error = ((raise NameError, msg) rescue $!)
    error.to_s.object_id # => 17177860
    error.to_s.object_id # => 17177860
    ```

In the second example, `Exception#to_s` will have a duplicate message if it's called more than once since [did_you_mean makes a disruptive change to the error message](https://github.com/yuki24/did_you_mean/blob/6265cc8718327856cf122b3585547d1ef0cc910a/lib/did_you_mean/core_ext/name_error.rb#L20).
