### ISSUE TITLE
SystemStackError in did_you_mean gem when using `undef`

### ISSUE THREAD

**Issue by presidentbeef** [yuki24/did_you_mean#56]
This is with `ruby 2.3.0preview1 (2015-11-11 trunk 52539) [x86_64-linux]` which uses `did_you_mean-1.0.0.beta3`. I was about to file a bug at bugs.ruby-lang.org but then thought here might be better.

Example:

```ruby
undef :a
```
Output when using `ruby -d`:
```
Exception `LoadError' at /home/justin/.rvm/rubies/ruby-2.3.0-preview1/lib/ruby/2.3.0/rubygems.rb:1241 - cannot load such file -- rubygems/defaults/operating_system
Exception `LoadError' at /home/justin/.rvm/rubies/ruby-2.3.0-preview1/lib/ruby/2.3.0/rubygems.rb:1250 - cannot load such file -- rubygems/defaults/ruby
Exception `LoadError' at /home/justin/.rvm/rubies/ruby-2.3.0-preview1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:54 - cannot load such file -- did_you_mean
Exception `SystemStackError' at /home/justin/.rvm/gems/ruby-2.3.0-preview1@global/gems/did_you_mean-1.0.0.beta3/lib/did_you_mean/core_ext/name_error.rb:10 - stack level too deep
/home/justin/.rvm/gems/ruby-2.3.0-preview1@global/gems/did_you_mean-1.0.0.beta3/lib/did_you_mean/core_ext/name_error.rb:10:in `to_s': stack level too deep (SystemStackError)
	from /home/justin/.rvm/gems/ruby-2.3.0-preview1@global/gems/did_you_mean-1.0.0.beta3/lib/did_you_mean/spell_checkers/method_name_checker.rb:15:in `initialize'
	from /home/justin/.rvm/gems/ruby-2.3.0-preview1@global/gems/did_you_mean-1.0.0.beta3/lib/did_you_mean/core_ext/name_error.rb:25:in `new'
	from /home/justin/.rvm/gems/ruby-2.3.0-preview1@global/gems/did_you_mean-1.0.0.beta3/lib/did_you_mean/core_ext/name_error.rb:25:in `spell_checker'
	from /home/justin/.rvm/gems/ruby-2.3.0-preview1@global/gems/did_you_mean-1.0.0.beta3/lib/did_you_mean/core_ext/name_error.rb:21:in `corrections'
	from /home/justin/.rvm/gems/ruby-2.3.0-preview1@global/gems/did_you_mean-1.0.0.beta3/lib/did_you_mean/core_ext/name_error.rb:14:in `to_s'
	from /home/justin/.rvm/gems/ruby-2.3.0-preview1@global/gems/did_you_mean-1.0.0.beta3/lib/did_you_mean/spell_checkers/method_name_checker.rb:15:in `initialize'
	from /home/justin/.rvm/gems/ruby-2.3.0-preview1@global/gems/did_you_mean-1.0.0.beta3/lib/did_you_mean/core_ext/name_error.rb:25:in `new'
	from /home/justin/.rvm/gems/ruby-2.3.0-preview1@global/gems/did_you_mean-1.0.0.beta3/lib/did_you_mean/core_ext/name_error.rb:25:in `spell_checker'
	 ... 9010 levels...
	from /home/justin/.rvm/gems/ruby-2.3.0-preview1@global/gems/did_you_mean-1.0.0.beta3/lib/did_you_mean/core_ext/name_error.rb:25:in `spell_checker'
	from /home/justin/.rvm/gems/ruby-2.3.0-preview1@global/gems/did_you_mean-1.0.0.beta3/lib/did_you_mean/core_ext/name_error.rb:21:in `corrections'
	from /home/justin/.rvm/gems/ruby-2.3.0-preview1@global/gems/did_you_mean-1.0.0.beta3/lib/did_you_mean/core_ext/name_error.rb:14:in `to_s'
	from test.rb:1:in `<main>'
```

This example came from trying to use `safe_yaml` which loads `psych/deprecated` which uses `undef` here: https://github.com/tenderlove/psych/blob/c1decb1fef5c77d84a93d5ac19a4961da914dd5c/lib/psych/deprecated.rb#L81

**Comment by yuki24** [comment]
@presidentbeef Thanks for reporting! I'll take a look.

**Comment by yuki24** [comment]
As of https://github.com/yuki24/did_you_mean/commit/d71740ac822af0badcbcefbe2ffc319068768a70, this gem no longer uses TracePoint API, thus this issue should be gone now. Thanks again for reporting!
