### ISSUE TITLE
Infinite Loop

### ISSUE THREAD

**Issue by braindev** [yuki24/did_you_mean#87]
I'm seeing an infinite loop.  It's happening here:

https://github.com/yuki24/did_you_mean/blob/master/lib/did_you_mean/core_ext/name_error.rb#L10

I am unsure what's causing it but I thought I'd report it just in case anyone else encounters the same issue.  FWIW, it's triggered in rspec reporting a `NoMethodError` error.

I'm seeing stack traces like this:

```
/usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/core_ext/name_error.rb:10:in `inspect'
/usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/core_ext/name_error.rb:10:in `inspect'
/usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/core_ext/name_error.rb:10:in `inspect'
/usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/core_ext/name_error.rb:10:in `inspect'
/usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/core_ext/name_error.rb:10:in `inspect'
/usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/core_ext/name_error.rb:10:in `inspect'
/usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/core_ext/name_error.rb:10:in `inspect'
/usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/core_ext/name_error.rb:10:in `inspect'
/usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/core_ext/name_error.rb:10:in `inspect'
/usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/core_ext/name_error.rb:10:in `inspect'
...
```

**Comment by yuki24** [comment]
Thanks for reporting. It seems like you are using an older version of DYM. Could you try upgrading to [1.0.3](https://rubygems.org/gems/did_you_mean/versions/1.0.3) and see if it fixes the issue?
